// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jisvpfaxmzvvlvefzgvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppc3ZwZmF4bXp2dmx2ZWZ6Z3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDA1NDgsImV4cCI6MjA1MzM3NjU0OH0.wqL9I1GNxKhEhaQnw6Gb6E9sJ5zEIYkyj7a_Am9jXJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);